version: '3.8'

services:
  web:
    env_file: env.example
    build: .
    command: uvicorn main:app --host 0.0.0.0 --port 80
    volumes:
      - .:/app
    ports:
      - "${DOCKER_EXPOSE_PORT:-8008}:80"